// Re-export only the icons used across the site.
// Named imports from lucide-react tree-shake correctly in production builds.
export {
  ArrowRight,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clipboard,
  Code2,
  Coffee,
  CodeXml,
  Download,
  ExternalLink,
  Linkedin,
  MapPin,
  FileSpreadsheet,
  Github,
  Globe,
  Keyboard,
  Lightbulb,
  Menu,
  MessageCircle,
  Monitor,
  Moon,
  Palette,
  Play,
  Search,
  ShieldCheck,
  Star,
  Sun,
  CircleCheck,
  Smartphone,
  Terminal,
  X,
  Zap,
} from 'lucide-react'
